IF (FANN_ROOT)
    # force re-find programs
    set(FANN_LIBRARY NOTFOUND CACHE FILE "" FORCE)
    set(FANN_INCLUDE_DIR NOTFOUND CACHE PATH "" FORCE)
ENDIF (FANN_ROOT)

FIND_LIBRARY(FANN_LIBRARY fann HINTS ${FANN_ROOT} PATH_SUFFIXES "lib") 
FIND_PATH(FANN_INCLUDE_DIR fann.h HINTS ${FANN_ROOT} PATH_SUFFIXES "include")

IF (FANN_INCLUDE_DIR AND FANN_LIBRARY)
   SET(FANN_FOUND TRUE)
ENDIF (FANN_INCLUDE_DIR AND FANN_LIBRARY)


IF (FANN_FOUND)
   IF (NOT FANN_FIND_QUIETLY)
      MESSAGE(STATUS "Found fann: ${FANN_LIBRARY}")
   ENDIF (NOT FANN_FIND_QUIETLY)
ELSE (FANN_FOUND)
   IF (FANN_FIND_REQUIRED)
      MESSAGE(WARNING "Could not find fann")
   ENDIF (FANN_FIND_REQUIRED)
ENDIF (FANN_FOUND)
